// Generated by BUCKLESCRIPT VERSION 1.6.0, PLEASE EDIT WITH CARE
'use strict';

var ImperialMetric = require("imperial-metric");

var result = ImperialMetric(1).from("km").to("inch");

console.log(result);

exports.result = result;
/* result Not a pure module */
