// Generated by BUCKLESCRIPT VERSION 1.6.0, PLEASE EDIT WITH CARE
'use strict';

var PixelCompare = require("pixel-compare");

PixelCompare({
        baseImage: "./src/dragon.png",
        testImage: "./src/dragon.png"
      }).then(function (res) {
      console.log(res);
      return /* () */0;
    });

/*  Not a pure module */
